#!/usr/bin/env bash

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)

pushd "${HERE}" >/dev/null || exit 1

PARENT_COMMAND=$(ps $PPID | tail -n 1 | awk "{print \$5}")
echo "*** wizbat caller : ${PARENT_COMMAND}"
echo "*** calling from  : ${HERE}  / = $(pwd)"
echo "*** using Python  : $(/home/pi/.pyenv/bin/pyenv which python)"

# shellcheck disable=SC1091
source ./src/include.sh

# check commandline parameters
for i in "$@"; do
    echo "*** wizbat option: ${i}"
    case $i in
    -i | --install)
        install_wizbat "${HERE}"
        ;;
    -u | --uninstall)
        unstall_wizbat
        ;;
    -s | --stop)
        stop_wizbat
        ;;
    -g | --go)
        start_wizbat "${HERE}" "-nograph"
        ;;
    -b | --boot)
        boot_wizbat
        ;;
    -r | --restart)
        restart_wizbat "${HERE}" 0
        ;;
    --systemd )
        restart_wizbat "${HERE}" 1
        ;;
    --graph)
        graph_wizbat "${HERE}"
        ;;
    --update)
        update_wizbat
        ;;
    *)
        # unknown option
        echo "** Unknown option **"
        echo
        echo "Syntax:"
        echo "wizbat [-i|--install] [-g|--go] [-r|--restart|--graph]  [-s|--stop] [-u|--uninstall]"
        echo
        exit 1
        ;;
    esac
done

popd >/dev/null || exit 1
